### ISSUE TITLE
Encoding error:  Not working 

### ISSUE THREAD

**Issue by politicus** [jlangston/SublimeHowDoI#4]
Hi, 

I just installed your HowDoI Sublime Text package. I tested "how do I" in iTerm and everything is working fine. 

In Sublime Text 3, I always get the error: 

`Traceback (most recent call last):
  File "/usr/local/bin/howdoi", line 11, in <module>
    sys.exit(command_line_runner())
  File "/usr/local/lib/python3.6/site-packages/howdoi/howdoi.py", line 267, in command_line_runner
    print(howdoi(args))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 802-803: ordinal not in range(128)`

Can you help me please? Thank you.

Sublime Text version: Sublime Text vBuild 3144 (3144)
OSX 10.10.

**Comment by jlangston** [comment]
Is there a particular query you were trying? It's working for me on OSX 10.10 currently
